config/routes.rb
Happygram::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "profiles/show"

  resources :comments

  as :user do
    get '/login', to: 'devise/sessions#new', as: :login
    get '/register', to: 'devise/registrations#new', as: :register
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :entries
    get 'feed', to: 'entries#index', as: :feed
    
  get "/entries/:id/add_entry_comment", to: "entries#add_entry_comment", as: :add_entry_comment
  get "/entries/:id/edit_entry_comment/:entry_comment_id", to: "entries#edit_entry_comment", as: :edit_entry_comment
  

  root to: 'entries#index'  

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_handle(params[:id])

  	if @user
  		@entries = @user.entries.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="row">
  <div class="span8 offset2">
  <div class="row">
    <div class="span1">
      <div class="happyprofile" style="background-image: url('<%= @user.profile_picture.url %>');">
        <%= link_to(image_tag(@user.profile_picture.url), profile_path(@user.handle), :style => "width:50px;") %>
      </div>
    </div>
    <div class="span6">
      <h1>
        <%= @user.full_name %>
      </h1>
    </div>
  </div>  
  <div class="row">
  	<div id="friend-entry">
      <div class="span1"></div>
      <div class="span6">
        <% if signed_in? && @user != current_user %>
          
          <% if @user.friends.count > 0 %>
            <%= @user.friends.count %> Friends<br>
          <% else %>
            <%= @user.first_name %> currently has no friends... Add them now!<br>
            <% if current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
              <%= link_to "Edit Friendship", edit_friendship_path(friend_id: @user), class: 'btn' %>
            <% else %>
              <%= link_to "Add #{@user.first_name}", new_friendship_path(friend_id: @user), class: 'btn', id: 'add-friendship', data: { friend_id: @user.to_param } %>
            <% end %>
          <% end %>
        <% else %>
          <% if @user.friends.count > 0 %>
            You have <%= @user.friends.count %> friends<br>
          <% else %>
            You have no friends... aww.<br>
          <% end %>
        <% end %>
        
      </div>
  	</div>
  </div>



<br />

<% if @entries.count > 0 %>
  <% @entries.each do |entry| %>
    <div class="well" style="width:515px;">
      <strong><%= entry.title %></strong>
      <div class="happypost" style="background-image: url('<%= entry.photo.url %>');">
        <%= link_to(image_tag(entry.photo.url), profile_path(entry.user.handle), :style => "width:500px;") %></p>
      </div><hr>
      <%= entry.description %></p>
      <hr />
      <%= link_to time_ago_in_words(entry.created_at), entry_path(entry) %> ago
    </div>
  <% end %>
<% else %>
  <h3>No posts yet. :(</h3>
<% end %>
</div>
</div>