config/routes.rb
Happygram::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "profiles/show"

  resources :comments

  as :user do
    get '/login', to: 'devise/sessions#new', as: :login
    get '/register', to: 'devise/registrations#new', as: :register
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :entries
    get 'feed', to: 'entries#index', as: :feed
    
  get "/entries/:id/add_entry_comment", to: "entries#add_entry_comment", as: :add_entry_comment
  get "/entries/:id/edit_entry_comment/:entry_comment_id", to: "entries#edit_entry_comment", as: :edit_entry_comment
  

  root to: 'entries#index'  

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	attr_accessible :title, :description, :photo, :user_id
	belongs_to :user
	has_many :comments
	
	validates :title, presence: :true
	validates :user_id, presence: :true	
	validates :photo, attachment_presence: true
	#, content_type: { content_type: ["image/jpg", "image/gif", "image/png"] }
	# validates_with AttachmentPresenceValidator, :attributes => :photo

	# validates_with AttachmentContentTypeValidator, :attributes => :photo

	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  #before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all.order("created_at DESC")
  
    # @friendships = Friendship.where("(user_account_id = ? AND status='Accepted')", current_user.id)
    # @friendships = FriendshipDecorator.decorate_collection(friendship_association.all)
    # @accepted = current_user.friendships.where(state: :accepted)
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  def new
    @entry = current_user.entries.new
  end

  # GET /entries/1/edit
  def edit
    @entry = current_user.entries.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Your entry has been posted!' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    @entry = current_user.entries.find(params[:id])
    
    if params[:entry] && params[:entry].has_key?(:user_id)
      params[:entry].delete(:user_id)
    end

    respond_to do |format|
      if @entry.update_attributes(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = current_user.entries.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  def add_entry_comment
      @entry = Entry.find(params[:id])
      @comment = Comment.new
      @comment.user_id = current_user.id
      @comment.entry_id = @entry.id
      render "comments/new"
  end

  def edit_entry_comment
      @entry = Entry.find(params[:id])
      @comment = Comment.find(params[:entry_comment_id])
      if @comment.user_id != current_user.id
        @comment = nil
      end
      render "comments/edit"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :description, :photo, :user_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= simple_form_for(@entry, html: {class: "form-horizontal", multipart: true}) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :description, input_html: { rows: 4, class: 'input-xxlarge' } %>
  <%= f.input :photo %>
  <div class="controls">
    <em>We recommend you to upload a square image so it won't be cropped. :)</em>
  </div>
  <div class="controls">
    <% if @entry.photo? %>
      <%= image_tag @entry.photo.url, style: "width:200px;" %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div class="page-header">
  <h1>All Entries</h1>
</div>

<%= link_to "Post a New Entry", new_entry_path, class: "btn" %>
<br><br>
<% @entries.each do |entry| %>
  <% if can_display_entry?(entry) %>
    <div class="entry">
      <div class="row">
        <div class="span1">
          <%= link_to image_tag(entry.user.gravatar_url), profile_path(entry.user.handle) %>
        </div>
        <div class="span7">
          <strong><%= entry.title %></strong> by <%= link_to entry.user.full_name, profile_path(entry.user.handle) %>
          <p>
            <div class="happypost" style="background-image: url('<%= entry.photo.url %>');">
              <%= link_to(image_tag(entry.photo.url), profile_path(entry.user.handle), :style => "width:500px;") %></p>
            </div>
          </p>
          <hr><%= link_to entry.user.username, profile_path(entry.user.handle) %> <%= entry.description %>
          <hr>
          <div class="meta">
            <%= link_to "#{time_ago_in_words(entry.created_at)} ago", entry %> | 
            <% if entry.comments.count == 1 %>
              <%= entry.comments.count %> comment
            <% elsif entry.comments.count > 1 %>
              <%= entry.comments.count %> comments
            <% end %>

      
            <% if signed_in? && entry.user == current_user %>
              <span class="admin"> | 
               <%= link_to "Edit", edit_entry_path(entry) %> | 
                <%= link_to "Delete", entry, method: :delete, confirm: "Are you sure you want to delete this entry?" %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<div class="row">
  <div class="span7 offset1">
    <%= page_header do %>
      <h1>
        <div class="happyprofile" style="background-image: url('<%= @entry.user.profile_picture.url %>');">
        <%= link_to(image_tag(@entry.user.profile_picture.url), profile_path(@entry.user.handle), :style => "width:50px;") %>
      </div>
        <%= @entry.user.full_name %><br>
        <small><%= time_ago_in_words(@entry.created_at) + " ago" %></small>
      </h1>
    <% end %>

    <strong><%= @entry.title %></strong>

    <p>
    	<div class="happypost" style="background-image: url('<%= @entry.photo.url %>');">
        <%= link_to(image_tag(@entry.photo.url), profile_path(@entry.user.handle), :style => "width:500px;") %></p>
      </div><hr><br>
      <%= @entry.description %>
    </p>

    <hr />
    <div class="meta">
      <%= link_to 'Back', entries_path %>
      <% if signed_in? && @entry.user == current_user %>
        |
        <%= link_to "Edit", edit_entry_path(@entry) %> | 
        <%= link_to "Delete", @entry, method: :delete, data: { confirm: "Are you sure your want to delete this entry?"} %>
      <% end %>
    </div>
    <hr>
    <h2>Comments</h2>
    <div class="well">
    <% @entry.comments.each do |post| %>
      <% @u = User.find(post.user_id) %>
      <%= link_to @u.full_name, profile_path(@u.handle) %><br>
      <%= post.content %>
      <% if signed_in? %>
        <% if current_user.id == post.user_id %><br>
          <%= link_to "Edit", edit_entry_comment_path(@entry.id,post.id) %>
          <%= link_to "Delete", comment_path(post.id), method: :delete, confirm: "Are you sure?" %>
        <% end %><hr>
      <% end %>
    <% end %>
    <% if signed_in? %>
    <%= link_to "Add Comment", add_entry_comment_path(@entry.id), class: "btn" %>
    <% end %>
  </div>
  </div>
</div>