config/routes.rb
Happygram::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "profiles/show"

  resources :comments

  as :user do
    get '/login', to: 'devise/sessions#new', as: :login
    get '/register', to: 'devise/registrations#new', as: :register
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :entries
    get 'feed', to: 'entries#index', as: :feed
    
  get "/entries/:id/add_entry_comment", to: "entries#add_entry_comment", as: :add_entry_comment
  get "/entries/:id/edit_entry_comment/:entry_comment_id", to: "entries#edit_entry_comment", as: :edit_entry_comment
  

  root to: 'entries#index'  

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
	attr_accessible :user_id, :friend_id, :user, :friend, :state

	after_destroy :delete_mutual_friendship!

	state_machine :state, initial: :pending do
		after_transition on: :accept, do: [:send_acceptance_email, :accept_mutual_friendship!]
		after_transition on: :block, do: [:block_mutual_friendship!]
		
		state :requested
		state :blocked
		
		event :accept do
			transition any => :accepted
		end

		event :block do
			transition any => :blocked
		end
	end

	validate :not_blocked

	def self.request(user1, user2)
		transaction do
			friendship1 = create(user: user1, friend: user2, state: 'pending')
			friendship2 = create(user: user2, friend: user1, state: 'requested')

			friendship1.send_request_email if !friendship1.new_record?
			friendship1
		end
	end

	def not_blocked
		if Friendship.exists?(user_id: user_id, friend_id: friend_id, state: 'blocked') || Friendship.exists?(user_id: friend_id, friend_id: user_id, state: 'blocked')
			errors.add(:base, "The friendship cannot be added.")	
		end
	end

	def send_request_email
		UserNotifier.friend_requested(id).deliver
	end

	def send_acceptance_email
		UserNotifier.friend_request_accepted(id).deliver
	end

	def mutual_friendship
		self.class.where({user_id:friend_id, friend_id: user_id}).first
		
	end

	def accept_mutual_friendship!
		# Grab the mutual friendship and update the state without using
		# the state machine so as not to invoke callbacks.
		# Ito sabi sa tutorial wtf does this mean I don't even
		mutual_friendship.update_attribute(:state, 'accepted')
	end

	def delete_mutual_friendship!
		mutual_friendship.delete
	end

	def block_mutual_friendship!
		mutual_friendship.update_attribute(:state, 'blocked') if mutual_friendship
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_filter :authenticate_user! #, only: [:new, :index]
	respond_to :html, :json

	def index
		@friendships = FriendshipDecorator.decorate_collection(friendship_association.all)
		@blocked = current_user.friendships.where(state: :blocked)
		@accepted = current_user.friendships.where(state: :accepted)
		@requested = current_user.friendships.where(state: :requested)
		@pending = current_user.friendships.where(state: :pending)

		respond_with @friendships
	end

	def accept
		@friendship = current_user.friendships.find(params[:id])
		if @friendship.accept!
			flash[:success] = "You are now friends with #{@friendship.friend.first_name}!"
		else
			flash[:error] = "That friendship could not be accepted. :("
		end
		redirect_to friendships_path
	end

	def block
		@friendship = current_user.friendships.find(params[:id])
		if @friendship.block!
			flash[:success] = "You have blocked #{@friendship.friend.first_name}."
		else
			flash[:error] = "That friendship could not be blocked."
		end
		redirect_to friendships_path
	end

	def new
		if params[:friend_id]
			@friend = User.where(handle: params[:friend_id]).first
			@friendship = current_user.friendships.new(friend: @friend)
		else
			flash[:error] = "Friend required"
		end
	rescue ActiveRecord::RecordNotFound
		render file: 'public/404', status: :not_found
	end

	def create
		if params[:friendship] && params[:friendship].has_key?(:friend_id)
			@friend = User.where(handle: params[:friendship][:friend_id]).first
			@friendship = Friendship.request(current_user, @friend)
			respond_to do |format|
				if @friendship.new_record?
					format.html do
						flash[:error] = "There was a problem creating that friend request."
						redirect_to profile_path(@friend)
					end
					format.json { render json: @friendship.to_json, status: :precondition_failed }
				else
					format.html do
						flash[:success] = "Friend request sent!"
						redirect_to profile_path(@friend)
					end
					format.json { render json: @friendship.to_json }
				end
			end
		else
			flash[:error] = "Friend required"
			redirect_to root_path
		end
	end

	def edit
			@friend = User.where(handle: params[:id]).first
			@friendship = current_user.friendships.where(friend_id: @friend.id).first.decorate
	end

	def destroy
		@friendship = current_user.friendships.find(params[:id])
		if @friendship.destroy
			flash[:success] = "Friendship destroyed."
		end
		redirect_to friendships_path 
	end

	private
	def friendship_association
		case params[:list]
		when nil
			current_user.friendships
		when 'blocked'
			current_user.blocked_friendships
		when 'pending'
			current_user.pending_friendships
		when 'accepted'
			current_user.accepted_friendships
		when 'requested'
			current_user.requested_friendships
		end
	end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/edit.html.erb
<div class="page-header">
	<h1>Viewing Friendship</h1>
</div>

<div class="row">
	<div class="avatar span2">
		<%= image_tag @friendship.user.gravatar_url %><br>
		<%= @friendship.user.first_name %>
	</div>
	<div class="avatar span2">
		<%= image_tag @friendship.friend.gravatar_url %><br>
		<%= @friendship.friend.first_name %>
	</div>
</div>
<hr>

<h3><%= @friendship.sub_message %></h3>

<div class="form-actions">
	<% if @friendship.requested? %>
    <%= form_for @friendship, url: accept_friendship_path(@friendship), method: :put do |form| %>
      <%= submit_tag "Confirm", class: 'btn btn-primary' %>
    <% end %>
    <%= form_for @friendship, url: friendship_path(@friendship), method: :delete do |form| %>
	      <%= submit_tag "Ignore", class: 'btn btn-danger' %>
	  <% end %>
  <% end %>

  <% if @friendship.blocked? %>
  	<%= form_for @friendship, url: friendship_path(@friendship), method: :delete do |form| %>
      <%= submit_tag "Unblock", class: 'btn btn-primary' %>
    <% end %>
  <% else %>
	  <%= form_for @friendship, url: block_friendship_path(@friendship), method: :put do |form| %>
  	  <%= submit_tag "Block", class: 'btn' %>
  	<% end %>
  <% end %>

  <% if @friendship.accepted? %>
	  <%= form_for @friendship, url: friendship_path(@friendship), method: :delete do |form| %>
	      <%= submit_tag "Unfriend", class: 'btn btn-danger' %>
	  <% end %>
  <% end %>

  <% if @friendship.pending? %>
	  <%= form_for @friendship, url: friendship_path(@friendship), method: :delete do |form| %>
	      <%= submit_tag "Cancel Friend Request", class: 'btn btn-danger' %>
	  <% end %>
  <% end %>
</div>

app/views/friendships/index.html.erb
<div class="page-header">
  <h1>My Friends</h1>
</div>

<ul class="nav nav-pills" id="friend-list-filter">
  <li class="<%= 'active' if params[:list] == '' || params[:list].blank? %>">
    <%= link_to 'All', friendships_path %>
  </li>  
  <li class="<%= 'active' if params[:list] == 'blocked' %>">
    <% if @blocked.count > 0 %>
      <%= link_to "Blocked (#{@blocked.count})", friendships_path(list: 'blocked') %>
    <% else %>
      <%= link_to "Blocked", friendships_path(list: 'blocked') %>
    <% end %>
  </li>  
  <li class="<%= 'active' if params[:list] == 'requested' %>">
    <% if @requested.count > 0 %>
      <%= link_to "Requested (#{@requested.count})", friendships_path(list: 'requested') %>
    <% else %>
      <%= link_to "Requested", friendships_path(list: 'requested') %>
    <% end %>
  </li>
  <li class="<%= 'active' if params[:list] == 'accepted' %>">
    <% if @accepted.count > 0 %>
      <%= link_to "Accepted (#{@accepted.count})", friendships_path(list: 'accepted') %>
    <% else %>
      <%= link_to "Accepted", friendships_path(list: 'accepted') %>
    <% end %>
  </li>
  <li class="<%= 'active' if params[:list] == 'pending' %>">
    <% if @pending.count > 0 %>
      <%= link_to "Pending (#{@pending.count})", friendships_path(list: 'pending') %>
    <% else %>
      <%= link_to "Pending", friendships_path(list: 'pending') %>
    <% end %>
  </li>
</ul>

<hr />

<div id="friend-list">
<% @friendships.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="media friend">
    <%= link_to image_tag(friend.gravatar_url), profile_path(friend), class: 'pull-left' %>
    <div class="media-body">
      <h4 class="media-heading"><%= friend.full_name %></h4>
      <em>Friendship is <%= friendship.state %></em>. <br />
      <%= link_to "#{friendship.update_action_verbiage}", edit_friendship_path(friendship.friend.handle), class: 'btn btn-small' %>
    </div>
  </div>
<% end %>
</div>

app/views/friendships/new.html.erb
<% if @friend %>
	<h1><%= @friend.full_name %></h1>

	<p>Do you really want to add <%= @friend.full_name %>?</p>

	<%= form_for @friendship, method: :post do |form| %>
		<div class="form form-actions">
			<%= form.hidden_field :friend_id, value: @friend.handle %>
			<%= submit_tag "Yes, Add Friend", class: 'btn btn-primary' %>
			<%= link_to "Cancel", profile_path(@friend), class: 'btn' %>
		</div>
	<% end %>
<% end %>