config/routes.rb
Happygram::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "profiles/show"

  resources :comments

  as :user do
    get '/login', to: 'devise/sessions#new', as: :login
    get '/register', to: 'devise/registrations#new', as: :register
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :entries
    get 'feed', to: 'entries#index', as: :feed
    
  get "/entries/:id/add_entry_comment", to: "entries#add_entry_comment", as: :add_entry_comment
  get "/entries/:id/edit_entry_comment/:entry_comment_id", to: "entries#edit_entry_comment", as: :edit_entry_comment
  

  root to: 'entries#index'  

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Merienda+One' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
	<!--  -->
	<title>Happygram</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<span class="brand">
					<%= link_to (image_tag "HEADER_FOOTER/HeaderLogo.png"), root_path %></span>
				<ul class="nav pull-right" style ="font-family:'Montserrat';">
					<% if user_signed_in? %>
						<li><%= link_to (image_tag("HEADER_FOOTER/Home.png")+"Feed").html_safe, feed_path %></li>
						<li><%= link_to "Friends", friendships_path %></li>
						<li><%= link_to (image_tag(current_user.profile_picture.url, class: "avatar-nav")+ " " +current_user.full_name).html_safe, "/#{current_user.handle}" %>
						</li>
						<li><%= link_to (image_tag("HEADER_FOOTER/Logout.png")+"Log out"), logout_path, confirm: "Are you sure you want to logout? :(" %>
						</li>
					<% else %>
						<li><%= link_to (image_tag("HEADER_FOOTER/About.png")+"About").html_safe, "#" %></li>
						<li><%= link_to (image_tag("HEADER_FOOTER/Login.png")+"Sign up").html_safe, register_path %></li>
						<li><%= link_to (image_tag("HEADER_FOOTER/Login.png")+"Log in"), login_path %></li>
					<% end %>
				</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<% flash.each do |type, message| %>
				<div class="alert <%= flash_class type %>">
					<button class="close" data-dismiss="alert">x</button>
					<%= message %>
				</div>
			<% end %>
			<%= yield %>
		</div>
	</body>
	</html>